= POSIX
Ayman Patel
:toc:
:icons: font

> Portable Operating System Interface

== What is POSIX?

Portable Operating System Interface (POSIX) is a family of standards specified by the IEEE for maintaining compatibility between OS. POSIX defines the API, along with command line shells and utility interfaces, for software compatibility with variants of Unix and other OSes.



== bashisms

*bashisms* are Bash-specific constructs which are not understood by other shells, such as Dash (the default system shell in Debian and Ubuntu)

http://mywiki.wooledge.org/Bashism[Bashism wiki]

== Gotchas

=== POSIX and Bashisms

1. Remember POSIX are https://stackoverflow.com/questions/40916071/making-unix-shell-scripts-posix-compliant[NOT bash-compliant]. We need to remove *bashisms* from bash script to make it POSIX-compliant. 


=== Why are most Linux distros "Mostly-POSIX compliant"

POSIX are of 2 type: 
1. POSIX compliant
2. Mostly POSIX compliant

Most Linux distros are *"Mostly-POSIX compliant"* because of high fees to become completely POSIX compliant.

So instead, most of then choose to:

1. Trying to conform to POSIX.
2. Document non-conformance to POSIX.
3. Document extensions to POSIX.

https://unix.stackexchange.com/a/293436/295064[Link]
